font_family      Hasklug Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size        14.0

# hides tab bar when only one tab is present
show_tab_bar_margin      yes
tab_bar_edge             top
tab_bar_style            fade
hide_window_decorations  yes
tab_bar_min_tabs         2

# gruvbox dark theme
include ./kitty-themes/themes/gruvbox_dark.conf

window_padding_width 5
